config/routes.rb
Rails.application.routes.draw do

  get 'landings/index'

  resources :storefront

  resources :campaigns

  resources :pages

  resources :themes

  resources :collections

  resources :shops

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  get 'choose_site' => 'landings#choose_site'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
  has_many :campaigns

  validates :title, :description, :url, :presence => true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in

  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.where(["user_id = ?",current_user.id])
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :user_id, :description, :sold_count, :shirt_names, :url, :shop_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<% if @collection.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(@collection.errors.count, "error") %>:
    <ul>
    <% @collection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @collection, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>*
    <div class="col-md-10">
      <%= f.text_area :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>*
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sold_count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :sold_count, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shirt_names, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :shirt_names, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-md-2' %>*
    <div class="col-md-10">
      <%= f.text_field :url, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shop_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select :shop_id, Shop.where(["user_id = ?",current_user.id]), :id, :title, {include_blank: true} %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  collections_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

<br/><br/><br/><br/>

app/views/collections/edit.html.erb
<%- model_class = Collection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Collection %></h1>
</div>
<%= render :partial => 'form' %>

app/views/collections/index.html.erb
<%- model_class = Collection -%>
<div class="page-header">
  <h1><%=t '.title', :default => Collection %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:sold_count) %></th>
      <th><%= model_class.human_attribute_name(:shirt_names) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:shop_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.id %></td>
        <td><%= collection.title %></td>
        <td><%= collection.description %></td>
        <td><%= collection.sold_count %></td>
        <td><%= collection.shirt_names %></td>
        <td><%= collection.url %></td>
        <td><%= collection.shop_id %></td>
        <td><%=l collection.created_at, format: :long %></td>
        <td>
          <%= link_to collection_path(collection), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to collection_path(collection), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_collection_path,
            :class => 'btn btn-primary' %>

app/views/collections/new.html.erb
<%- model_class = Collection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Collection %></h1>
</div>
<%= render :partial => 'form' %>

app/views/collections/show.html.erb
<%- model_class = Collection -%>
<div class="page-header">
  <h1><%=t '.title', :default => Collection %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @collection.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @collection.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sold_count) %></dt>
      <dd><pre class="prettyprint"><%= @collection.sold_count %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:shirt_names) %></dt>
      <dd><pre class="prettyprint"><%= @collection.shirt_names %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:url) %></dt>
      <dd><pre class="prettyprint"><%= @collection.url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:shop_id) %></dt>
      <dd><pre class="prettyprint"><%= @collection.shop_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              collections_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_collection_path(@collection), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              collection_path(@collection),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>